name: actions
on:
  workflow_dispatch:

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        id: step1
        with:
          fetch-depth: '0'
      - name: Print the depth
        run: echo ${{ steps.step1.ref }}