name: actions
on:
  workflow_dispatch:

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        id: step1
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Print the depth
        run: echo ${{ steps.step1.outputs.ref }}