name: actions
on:
  workflow_dispatch:

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout my repository
        uses: actions/checkout@v4

      - name: Validate yaml files in my repo
        uses: GrantBirki/json-yaml-validate@v3.3.0
