name: matrix_demo
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: select the environment
        options:
          - DEV
          - QA
          - UAT
          - PROD

env:
  ENV: ${{ inputs.environment }}
  PASS: ${{ secrets.MY_NAME }}

jobs:
  demo:
    strategy:
      matrix:
        version: [14 , 15, 16]
    runs-on: ubuntu-latest
    steps:
      - name: Print out the version
        run: echo ${{ matrix.version }}



