name: secrets
on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        type: string
        description: Enter the username

env:
  username: ${{ inputs.username }}

jobs:
  print:
    runs-on: [ self-hosted,Google ]
    steps:
      - uses: actions/checkout@v4
      - name: Print the username and password
        run: |
          echo "$username"
          echo "Password is ${{ secrets.MY_NAME }}"