name: third
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - closed
  workflow_dispatch:
    inputs:
      Environment:
        description: Enter the environment name
        required: true
        type: choice
        options:
          - dev
          - qa
          - uat



jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: test step
        run: sleep 20; echo "Hello World"; sleep 20; echo "Bye world"

      - name: second step
        run: ls -l

  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: test sleep
        run: sleep 30; echo "Hello India"; sleep 30; echo "Bye India"

  third_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: print the environment name
        run: echo $Environment