name: third
on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: test step
        run: sleep 20; echo "Hello World"; sleep 20; echo "Bye world"

      - name: second step
        run: ls -l

  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: test sleep
        run: sleep 30; echo "Hello India"; sleep 30; echo "Bye India"